name: Build SwiftUI Unsigned iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare SwiftUI App
        run: |
          mkdir -p source/MyApp
          cd source/MyApp

          # Create Info.plist
          cat > Info.plist <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>MyApp</string>
  <key>CFBundleIdentifier</key><string>com.hecarim.myapp</string>
  <key>CFBundleExecutable</key><string>MyApp</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>MinimumOSVersion</key><string>15.0</string>
</dict>
</plist>
PLIST

          # Create main.swift (entry point)
          cat > main.swift <<'SWIFT'
import SwiftUI

@main
struct MyApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    @State private var counter = 0
    var body: some View {
        VStack(spacing: 20) {
            Text("Hello from GitHub Actions 👋")
                .font(.title2)
            Text("Tapping \(counter) times")
                .foregroundColor(.secondary)
            Button("Tap me!") { counter += 1 }
                .buttonStyle(.borderedProminent)
        }
        .padding()
    }
}
SWIFT

      - name: Build unsigned IPA
        run: |
          cd source/MyApp
          mkdir -p build Payload
          echo "Building SwiftUI app (unsigned)..."
          xcodebuild -scheme MyApp -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO || true
          mkdir -p Payload/MyApp.app
          cp -r Info.plist main.swift Payload/MyApp.app/
          zip -r MyApp-unsigned.ipa Payload

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-unsigned
          path: source/MyApp/MyApp-unsigned.ipa
