name: Sanity check (YAML valid)

on:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run simple checks
        run: |
          echo "Sanity run: workflow file is valid"
          echo "User: $(whoami)"
          echo "PWD: $(pwd)"
          uname -a
          ls -la
