name: Build SwiftUI Unsigned App (Compiled)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare project files
        run: |
          mkdir -p source/MyApp/Payload/MyApp.app
          cd source/MyApp/Payload/MyApp.app

          # Info.plist
          cat > Info.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>MyApp</string>
  <key>CFBundleIdentifier</key><string>com.hecarim.myapp</string>
  <key>CFBundleExecutable</key><string>MyApp</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>MinimumOSVersion</key><string>15.0</string>
</dict>
</plist>
EOF

          # Swift source
          cat > main.swift <<EOF
import SwiftUI
@main
struct MyApp: App {
    var body: some Scene {
        WindowGroup {
            VStack(spacing: 20) {
                Text("🔥 Hello Hecarim!")
                    .font(.title)
                Text("Built fully on iPhone via GitHub Actions!")
                    .foregroundColor(.secondary)
                Button("Tap me!") { print("Tapped!") }
                    .buttonStyle(.borderedProminent)
            }
            .padding()
        }
    }
}
EOF

      - name: Compile Swift app
        run: |
          cd source/MyApp/Payload/MyApp.app
          swiftc -target arm64-apple-ios15.0 -sdk $(xcrun --sdk iphoneos --show-sdk-path) main.swift -o MyApp

      - name: Package unsigned IPA
        run: |
          cd source/MyApp
          zip -r ../../MyApp-unsigned.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-unsigned
          path: MyApp-unsigned.ipa
